# -*- coding: utf-8 -*-
# Copyright (c) bNovate (Douglas Watson)
# For license information, please see license.txt

import json
import frappe
import requests

mock = json.loads("""
{
  "data": [
    {
      "static_monitoring": 0,
      "io_monitoring": 60,
      "pin_state": "READY",
      "oc_output_cfg": "oc_output_cfg",
      "accuracy": 1,
      "is_facelift": false,
      "data_credit_type_name": "Free Connection Data pack 150GB 10y.",
      "mcc": "246",
      "lac": "146",
      "user_set_longitude": 14.269965,
      "iccid": "11111111111111111111",
      "monitoring_enabled": true,
      "hotspot_monitoring": 300,
      "mqtt": 1,
      "analog_input": "analog_input",
      "management_credit_type_name": "Paid Management pack 5y.",
      "auto_extend_credit": true,
      "model": "RUT950",
      "id": 70810,
      "signal": -81,
      "cell_id": "1037079",
      "cell_tower_longitude": 14.269965,
      "longitude": 14.269965,
      "satellites": 2,
      "management_credit_type": "management_5y",
      "cell_tower_latitude": 48.790625,
      "credit_type": "Free",
      "tags": [
        {
          "company_id": 430,
          "updated_at": {},
          "user_id": 4,
          "name": "The tag",
          "description": "Good tag",
          "created_at": {},
          "id": 11
        },
        {
          "company_id": 430,
          "updated_at": {},
          "user_id": 4,
          "name": "The tag",
          "description": "Good tag",
          "created_at": {},
          "id": 11
        }
      ],
      "data_credit_type": "data_150GB_10y",
      "wireless_monitoring": 60,
      "credit_enabled": true,
      "credit_activated": true,
      "analog_current_loop": 3.616076749251911,
      "company_name": "Company",
      "bootloader_version": "3.0.1",
      "last_update_at": {},
      "name": "RUT Device 1",
      "modem_manufacturer": "Quectel",
      "network_state": "Home",
      "relay_output_2": 0,
      "relay_output_cfg": "relay_output_cfg",
      "digital_open_collector_output_4pin": 9,
      "status": 1,
      "wan_state": "Mobile",
      "relay_output": "relay_output",
      "fix_status": true,
      "gps_time": 1,
      "batch_number": "0054",
      "latitude": 48.790625,
      "description": "s/n 0000000000, added at 2020-01-01",
      "created_at": {},
      "imsi": "246020102200857",
      "connection_state": "connected",
      "product_code": "RUT955H7VXXX",
      "mac": "00:00:00:00:00:00",
      "speed": 4.145608029883936,
      "data_credit_type_id": 6,
      "hardware_revision": "1307",
      "mobile_ip": "0.0.0.0",
      "updated_at": {},
      "cell_tower_accuracy": 14.269965,
      "temperature": 360,
      "digital_input": "digital_input",
      "last_connection_at": {},
      "credit_expire_date": {},
      "course": 7.386281948385884,
      "digital_isolated_input": "digital_isolated_input",
      "firmware": "RUT9XX_R_00.06.05.3",
      "modem_firmware": "EC25EFAR02A08M4G",
      "ddns_rules_count": 3,
      "wlan_mac": "00:00:00:00:00:00",
      "sim_slot": 1,
      "user_set_latitude": 48.790625,
      "gps_monitoring": 300,
      "mnc": "146",
      "company_id": 7034,
      "connection_type": "LTE",
      "operator_number": "24602",
      "connection_uptime": 3012,
      "dry_wet_input1": 2,
      "digital_inout2": 5,
      "sim_state": "inserted",
      "dry_wet_input0": 5,
      "management_credit_type_id": 2,
      "dynamic_monitoring": 300,
      "activation_status": "11111",
      "digital_inout0": 6,
      "serial": "0000000000",
      "modem_model": "EC25",
      "digital_inout1": 1,
      "router_uptime": 3060,
      "wan_ip": "0.0.0.0",
      "imei": "111111111111111",
      "digital_non_isolated_input_4pin": 7,
      "open_collector_output": "open_collector_output"
    },
    {
      "static_monitoring": 0,
      "io_monitoring": 60,
      "pin_state": "READY",
      "oc_output_cfg": "oc_output_cfg",
      "accuracy": 1,
      "is_facelift": false,
      "data_credit_type_name": "Free Connection Data pack 150GB 10y.",
      "mcc": "246",
      "lac": "146",
      "user_set_longitude": 14.269965,
      "iccid": "11111111111111111111",
      "monitoring_enabled": true,
      "hotspot_monitoring": 300,
      "mqtt": 1,
      "analog_input": "analog_input",
      "management_credit_type_name": "Paid Management pack 5y.",
      "auto_extend_credit": true,
      "model": "RUT950",
      "id": 70810,
      "signal": -81,
      "cell_id": "1037079",
      "cell_tower_longitude": 14.269965,
      "longitude": 14.269965,
      "satellites": 2,
      "management_credit_type": "management_5y",
      "cell_tower_latitude": 48.790625,
      "credit_type": "Free",
      "tags": [
        {
          "company_id": 430,
          "updated_at": {},
          "user_id": 4,
          "name": "The tag",
          "description": "Good tag",
          "created_at": {},
          "id": 11
        },
        {
          "company_id": 430,
          "updated_at": {},
          "user_id": 4,
          "name": "The tag",
          "description": "Good tag",
          "created_at": {},
          "id": 11
        }
      ],
      "data_credit_type": "data_150GB_10y",
      "wireless_monitoring": 60,
      "credit_enabled": true,
      "credit_activated": true,
      "analog_current_loop": 3.616076749251911,
      "company_name": "Company",
      "bootloader_version": "3.0.1",
      "last_update_at": {},
      "name": "RUT Device 1",
      "modem_manufacturer": "Quectel",
      "network_state": "Home",
      "relay_output_2": 0,
      "relay_output_cfg": "relay_output_cfg",
      "digital_open_collector_output_4pin": 9,
      "status": 1,
      "wan_state": "Mobile",
      "relay_output": "relay_output",
      "fix_status": true,
      "gps_time": 1,
      "batch_number": "0054",
      "latitude": 48.790625,
      "description": "s/n 0000000000, added at 2020-01-01",
      "created_at": {},
      "imsi": "246020102200857",
      "connection_state": "connected",
      "product_code": "RUT955H7VXXX",
      "mac": "00:00:00:00:00:00",
      "speed": 4.145608029883936,
      "data_credit_type_id": 6,
      "hardware_revision": "1307",
      "mobile_ip": "0.0.0.0",
      "updated_at": {},
      "cell_tower_accuracy": 14.269965,
      "temperature": 360,
      "digital_input": "digital_input",
      "last_connection_at": {},
      "credit_expire_date": {},
      "course": 7.386281948385884,
      "digital_isolated_input": "digital_isolated_input",
      "firmware": "RUT9XX_R_00.06.05.3",
      "modem_firmware": "EC25EFAR02A08M4G",
      "ddns_rules_count": 3,
      "wlan_mac": "00:00:00:00:00:00",
      "sim_slot": 1,
      "user_set_latitude": 48.790625,
      "gps_monitoring": 300,
      "mnc": "146",
      "company_id": 7034,
      "connection_type": "LTE",
      "operator_number": "24602",
      "connection_uptime": 3012,
      "dry_wet_input1": 2,
      "digital_inout2": 5,
      "sim_state": "inserted",
      "dry_wet_input0": 5,
      "management_credit_type_id": 2,
      "dynamic_monitoring": 300,
      "activation_status": "11111",
      "digital_inout0": 6,
      "serial": "0000000000",
      "modem_model": "EC25",
      "digital_inout1": 1,
      "router_uptime": 3060,
      "wan_ip": "0.0.0.0",
      "imei": "111111111111111",
      "digital_non_isolated_input_4pin": 7,
      "open_collector_output": "open_collector_output"
    }
  ],
  "success": true,
  "meta": {
    "total": 1420
  }
}
""")

@frappe.whitelist()
def simbase_get_cards():
    settings = frappe.get_single("bNovate Settings")
    return requests.request(
        "GET", 
        "https://api.simbase.com/simcards", 
        headers={"x-api-key": settings.simbase_api_key}
    ).json()

@frappe.whitelist()
def rms_get_devices():
    settings = frappe.get_single("bNovate Settings")
    return mock
    return requests.request(
        "GET", 
        "https://rms.teltonika-networks.com/api/devices", 
        headers={"Authorization": "Bearer {}".format(settings.rms_api_token)}
    ).json()



